name: Deploy fry-foundation to Production server

on:
  push:
    branches:
      - main  

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up SSH key
      #   uses: webfactory/ssh-agent@v0.6.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout code using SSH
        uses: actions/checkout@v4
        with:
          repository: Fry-Foundation/fry-market-backend
          # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false
          clean: true
          fetch-depth: 1

      - name: Install dependencies for deployment
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          
      - name: Create .ssh directory and add GitHub.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: |
          echo "Running tests..."
          if [ -f "test_cases.py" ]; then
            python test_cases.py
          else
            echo "No test cases file found"
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Server
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.PRODUCTION_SSH_PASSWORD }}
          HOST_IP: ${{ secrets.PRODUCTION_HOST_IP }}
          TARGET_DIR: '/root/production_Env/fry-network-python'
        run: |
          # Ensure .ssh directory exists and add your server's host key to known_hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H $HOST_IP >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          
          # SSH to the server and execute deployment steps
          sshpass -p "$SSH_PASSWORD" ssh -t -o StrictHostKeyChecking=no $SSH_USERNAME@$HOST_IP << EOF
            set -e
            echo "Deploying to production"
            
            # Check if the target directory exists and is a Git repository
            if [ ! -d "$TARGET_DIR/.git" ]; then
              echo "Directory is empty or not a Git repository. Cloning repository..."
              rm -rf "$TARGET_DIR"
              mkdir -p "$TARGET_DIR"
              git clone git@github.com:Fry-Foundation/fry-market-backend.git "$TARGET_DIR"
            else
              echo "Repository exists. Fetching latest changes..."
              cd "$TARGET_DIR"
              git remote set-url origin git@github.com:Fry-Foundation/fry-market-backend.git
              git fetch origin main
              git reset --hard origin/main
            fi
            
            # Verify the pulled files
            echo "Listing files in $TARGET_DIR after pulling code:"
            cd "$TARGET_DIR"
            ls -la
            
            # Create or activate virtual environment
            if [ ! -d "myenv" ]; then
              python3.11 -m venv myenv
            fi
            source myenv/bin/activate
            
            # Install the latest requirements file
            if [ -f "requirements.txt" ]; then
              echo "Using requirements file: requirements.txt"
              pip install --upgrade pip
              pip install -r "requirements.txt"
            else
              echo "No requirements file found"
              exit 1
            fi
            
            # Clean pip cache
            pip cache purge
            
            # Restart the service
            sudo systemctl daemon-reload
            sudo systemctl restart fry-foundation-production.service 
            sudo systemctl status fry-foundation-production.service 
          EOF
        shell: bash

  nginx-config:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Configure and Restart Nginx
        run: |
          sudo apt install nginx -y
          sudo nginx -t
          sudo systemctl restart nginx
          sudo systemctl status nginx

  notify:
    runs-on: ubuntu-latest
    needs: nginx-config
    if: success()
    steps:
      - name: Notify Success
        run: |
          echo "🎉 Production deployment was successful! 🚀"
          echo "The latest changes have been deployed to production, and Nginx has been reconfigured."
