name: Deploy via Self-Hosted Runner


on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted  # Run on self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Stop and Remove Existing Container (if running)
        run: |
             CONTAINER_ID=$(docker ps -q --filter "name=fry-network-backend")
             if [ ! -z "$CONTAINER_ID" ]; then
             echo "Stopping and removing existing backend container..."
             docker stop fry-network-backend
             docker rm fry-network-backend
             else
             echo "No existing backend container found!"
             fi

  

      - name: Build & Run Docker Container
        run: |
          # Navigate to project directory
          cd /home/actionsuser/production_Env/actions-runner-prod/fry-network/fry-market-backend/fry-market-backend || { echo "Project folder not found!"; exit 1; }
     

      - name: Build Docker image and run container
        run: |
             docker build -t fry-network  .
             docker run -d -p 6000:6000 --name=fry-network-backend fry-network


          

      - name: Cleanup Old Docker Images
        run: |
          echo "Removing old unused Docker images..."
          docker image prune -af
          echo "Cleanup completed!"

  nginx:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Nginx Configuration
        run: |
           sudo nginx -t
           sudo systemctl restart nginx
